### ISSUE TITLE
你好 能问下这个authkey的url是从哪找的吗

### ISSUE THREAD

**Issue by rnsw** [Bailuqiao/genshin-gacha-url#1]
这个 https://api-takumi.mihoyo.com/binding/api/genAuthKey
各种方法都用了，从pc端找了半天都没找到这个

**Comment by rnsw** [comment]
找到了 之前一直没看app

**Comment by Bailuqiao** [comment]
这个url是我反编译别人的app得到的，他们并没有加壳，很轻松就拿到了，我只是看到github居然搜不到相关的接口，就把它上传上去，方便大家，手机抓包搞了好几天没搞定就放弃了。。

**Comment by rnsw** [comment]
刚看下在米游社app里 反编译后直接搜字符串能搜到，有点乱我也没看了
